# Default values for workflow-input-validator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
name: "web-app"
image:
  repository: image_name
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

containers:
  port: 80

service:
  type: LoadBalancer
  port: 80

hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60

secrets:
  name: web-secret
  mongoHost: mongohost

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 1024Mi
    ephemeral-storage: 3Gi
  requests:
    cpu: 500m
    memory: 1024Mi
    ephemeral-storage: 2Gi

nodeSelector: {}

tolerations: []

